"""schema baseline

Revision ID: 4831bb012783
Revises: eafb371929f8
Create Date: 2026-07-21 19:52:26.251616

"""

from typing import Sequence, Union

import sqlalchemy as sa

import app.models.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4831bb012783"
down_revision: str | Sequence[str] | None = "eafb371929f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_dirs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("archive_dir_id", sa.Integer(), nullable=True),
        sa.Column("recursive_permissions", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "archive_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("archive_dir_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "badges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("group", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "client_user_agents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("string", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("string"),
    )
    op.create_index(
        op.f("ix_client_user_agents_id"), "client_user_agents", ["id"], unique=False
    )
    op.create_table(
        "keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orgs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "p4x_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("iban", sa.String(), nullable=False),
        sa.Column("bic", sa.String(), nullable=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("init_date", app.models.types.FlexibleDate(), nullable=True),
        sa.Column("init_balance", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iban"),
    )
    op.create_table(
        "p4x_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("background_color", sa.String(), nullable=False),
        sa.Column("text_color", sa.String(), nullable=False),
        sa.Column("protected", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "p4x_fees",
        sa.Column("start", app.models.types.FlexibleDate(), nullable=False),
        sa.Column("fee", sa.Float(), nullable=False),
        sa.Column("protected", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("start"),
    )
    op.create_table(
        "p4x_partners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("iban", sa.String(), nullable=True),
        sa.Column("partner_type", sa.String(), nullable=False),
        sa.Column("partner_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iban"),
    )
    op.create_index(
        op.f("ix_p4x_partners_partner_id"), "p4x_partners", ["partner_id"], unique=False
    )
    op.create_table(
        "p4x_specialcontacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cn", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_email"),
        "password_reset_tokens",
        ["email"],
        unique=False,
    )
    op.create_table(
        "personal_access_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tokenable_type", sa.String(), nullable=False),
        sa.Column("tokenable_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_personal_access_tokens_id"),
        "personal_access_tokens",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personal_access_tokens_token"),
        "personal_access_tokens",
        ["token"],
        unique=True,
    )
    op.create_table(
        "request_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_ip", sa.String(), nullable=False),
        sa.Column("client_ips", sa.String(), nullable=True),
        sa.Column("client_user_agent_id", sa.Integer(), nullable=True),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("request_method", sa.String(), nullable=False),
        sa.Column("request_path", sa.String(), nullable=False),
        sa.Column("request_input", sa.String(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_content", sa.String(), nullable=True),
        sa.Column("memory_usage", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_request_logs_id"), "request_logs", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("group", sa.String(), nullable=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sent_emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from", sa.String(), nullable=True),
        sa.Column("to", sa.String(), nullable=True),
        sa.Column("cc", sa.String(), nullable=True),
        sa.Column("bcc", sa.String(), nullable=True),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("body", sa.String(), nullable=True),
        sa.Column("headers", sa.String(), nullable=True),
        sa.Column("attachments", sa.String(), nullable=True),
        sa.Column("mailer", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sent_emails_id"), "sent_emails", ["id"], unique=False)
    op.create_table(
        "standesdb_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_type", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("extension", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("sha256_hash", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("default", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_standesdb_images_id"), "standesdb_images", ["id"], unique=False
    )
    op.create_table(
        "states",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "archive_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("archive_dir_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("state_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["archive_dir_id"],
            ["archive_dirs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kontakttyp", sa.String(), nullable=False),
        sa.Column("anrede", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("couleurname", sa.String(), nullable=True),
        sa.Column("org_id", sa.String(), nullable=True),
        sa.Column("adresse_anschrift", sa.String(), nullable=True),
        sa.Column("adresse_plz", sa.String(), nullable=True),
        sa.Column("adresse_ort", sa.String(), nullable=True),
        sa.Column("adresse_land", sa.String(), nullable=True),
        sa.Column("zustellungen", sa.Boolean(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("rufnummer", sa.String(), nullable=True),
        sa.Column("datum", app.models.types.FlexibleDate(), nullable=True),
        sa.Column("datum_accuracy", sa.Integer(), nullable=True),
        sa.Column("anmerkungen", sa.Text(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("modified_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_contacts_id"), "contacts", ["id"], unique=False)
    op.create_table(
        "members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vortitel", sa.String(), nullable=True),
        sa.Column("vorname", sa.String(), nullable=True),
        sa.Column("nachname", sa.String(), nullable=True),
        sa.Column("nachname_geburt", sa.String(), nullable=True),
        sa.Column("nachtitel", sa.String(), nullable=True),
        sa.Column("couleurname", sa.String(), nullable=True),
        sa.Column("org_id", sa.String(), nullable=True),
        sa.Column("state_id", sa.String(), nullable=True),
        sa.Column("gruender", sa.Boolean(), nullable=True),
        sa.Column("entlassen", sa.Boolean(), nullable=True),
        sa.Column("verstorben", sa.Boolean(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("geburtsdatum", app.models.types.FlexibleDate(), nullable=True),
        sa.Column("geburtsdatum_accuracy", sa.Integer(), nullable=True),
        sa.Column("aufnahmedatum", app.models.types.FlexibleDate(), nullable=True),
        sa.Column("aufnahmedatum_accuracy", sa.Integer(), nullable=True),
        sa.Column("branderdatum", app.models.types.FlexibleDate(), nullable=True),
        sa.Column("branderdatum_accuracy", sa.Integer(), nullable=True),
        sa.Column("burschungsdatum", app.models.types.FlexibleDate(), nullable=True),
        sa.Column("burschungsdatum_accuracy", sa.Integer(), nullable=True),
        sa.Column(
            "philistrierungsdatum", app.models.types.FlexibleDate(), nullable=True
        ),
        sa.Column("philistrierungsdatum_accuracy", sa.Integer(), nullable=True),
        sa.Column("entlassungsdatum", app.models.types.FlexibleDate(), nullable=True),
        sa.Column("entlassungsdatum_accuracy", sa.Integer(), nullable=True),
        sa.Column("sterbedatum", app.models.types.FlexibleDate(), nullable=True),
        sa.Column("sterbedatum_accuracy", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("mkv_ogv_url", sa.String(), nullable=True),
        sa.Column("rufnummer_mobil", sa.String(), nullable=True),
        sa.Column("rufnummer_privat", sa.String(), nullable=True),
        sa.Column("rufnummer_beruf", sa.String(), nullable=True),
        sa.Column("zustellungen", sa.String(), nullable=True),
        sa.Column("adresse_privat_anschrift", sa.String(), nullable=True),
        sa.Column("adresse_privat_plz", sa.String(), nullable=True),
        sa.Column("adresse_privat_ort", sa.String(), nullable=True),
        sa.Column("adresse_privat_land", sa.String(), nullable=True),
        sa.Column("adresse_beruf_anschrift", sa.String(), nullable=True),
        sa.Column("adresse_beruf_plz", sa.String(), nullable=True),
        sa.Column("adresse_beruf_ort", sa.String(), nullable=True),
        sa.Column("adresse_beruf_land", sa.String(), nullable=True),
        sa.Column("arbeitgeber", sa.String(), nullable=True),
        sa.Column("taetigkeit", sa.String(), nullable=True),
        sa.Column("mitgliedschaften", sa.Text(), nullable=True),
        sa.Column("verbandchargen", sa.Text(), nullable=True),
        sa.Column("anmerkungen", sa.Text(), nullable=True),
        sa.Column("grabadresse", sa.String(), nullable=True),
        sa.Column("chroniclemail", sa.Boolean(), nullable=True),
        sa.Column("p4x_init_date", app.models.types.FlexibleDate(), nullable=True),
        sa.Column("p4x_init_balance", sa.Integer(), nullable=True),
        sa.Column("p4x_freed", sa.Boolean(), nullable=True),
        sa.Column("p4x_comment", sa.String(), nullable=True),
        sa.Column("auth_password", sa.String(), nullable=True),
        sa.Column("auth_lastlogin_provider", sa.String(), nullable=True),
        sa.Column("auth_lastlogin", sa.DateTime(), nullable=True),
        sa.Column("auth_lastsignal", sa.DateTime(), nullable=True),
        sa.Column("auth_lastlogout", sa.DateTime(), nullable=True),
        sa.Column("auth_locked", sa.Boolean(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("modified_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["states.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_members_email"), "members", ["email"], unique=True)
    op.create_index(op.f("ix_members_id"), "members", ["id"], unique=False)
    op.create_table(
        "p4x_category_filters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("p4x_account_id", sa.Integer(), nullable=False),
        sa.Column("iban", sa.String(), nullable=True),
        sa.Column("min_amount", sa.Float(), nullable=True),
        sa.Column("max_amount", sa.Float(), nullable=True),
        sa.Column("subject_mode", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("p4x_category_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["p4x_account_id"],
            ["p4x_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["p4x_category_id"],
            ["p4x_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_p4x_category_filters_p4x_account_id"),
        "p4x_category_filters",
        ["p4x_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_p4x_category_filters_p4x_category_id"),
        "p4x_category_filters",
        ["p4x_category_id"],
        unique=False,
    )
    op.create_table(
        "p4x_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sha256hash", sa.String(), nullable=False),
        sa.Column("booking", app.models.types.FlexibleDate(), nullable=False),
        sa.Column("valuation", app.models.types.FlexibleDate(), nullable=False),
        sa.Column("iban", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("p4x_account_id", sa.Integer(), nullable=False),
        sa.Column("delegating_partner_type", sa.String(), nullable=True),
        sa.Column("delegating_partner_id", sa.Integer(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("raw", sa.Text(), nullable=True),
        sa.Column("attachment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["p4x_account_id"],
            ["p4x_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256hash"),
    )
    op.create_index(
        op.f("ix_p4x_transactions_amount"), "p4x_transactions", ["amount"], unique=False
    )
    op.create_index(
        op.f("ix_p4x_transactions_booking"),
        "p4x_transactions",
        ["booking"],
        unique=False,
    )
    op.create_index(
        op.f("ix_p4x_transactions_delegating_partner_id"),
        "p4x_transactions",
        ["delegating_partner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_p4x_transactions_delegating_partner_type"),
        "p4x_transactions",
        ["delegating_partner_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_p4x_transactions_iban"), "p4x_transactions", ["iban"], unique=False
    )
    op.create_index(
        op.f("ix_p4x_transactions_p4x_account_id"),
        "p4x_transactions",
        ["p4x_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_p4x_transactions_subject"),
        "p4x_transactions",
        ["subject"],
        unique=False,
    )
    op.create_index(
        op.f("ix_p4x_transactions_valuation"),
        "p4x_transactions",
        ["valuation"],
        unique=False,
    )
    op.create_table(
        "archive_file_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("archive_file_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["archive_file_id"],
            ["archive_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "archive_store_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_name", sa.String(), nullable=True),
        sa.Column("original_description", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("extension", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("backedup_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256_hash"),
    )
    op.create_table(
        "contacts_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("modified_by", sa.Integer(), nullable=True),
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("old", sa.String(), nullable=True),
        sa.Column("new", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "members_badges",
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("badge_id", sa.Integer(), nullable=False),
        sa.Column("presentationdate", app.models.types.FlexibleDate(), nullable=True),
        sa.Column("presentationdate_accuracy", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["badge_id"],
            ["badges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("member_id", "badge_id"),
    )
    op.create_table(
        "members_keys",
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("key_id", sa.Integer(), nullable=False),
        sa.Column("presentationdate", app.models.types.FlexibleDate(), nullable=True),
        sa.Column("presentationdate_accuracy", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["key_id"],
            ["keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("member_id", "key_id"),
    )
    op.create_table(
        "members_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column("modified_by", sa.Integer(), nullable=True),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("old", sa.String(), nullable=True),
        sa.Column("new", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "members_oauth2bindings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("remote_id", sa.String(), nullable=False),
        sa.Column("remote_name", sa.String(), nullable=False),
        sa.Column("bound_at", sa.DateTime(), nullable=True),
        sa.Column("lastuse_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_members_oauth2bindings_id"),
        "members_oauth2bindings",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_members_oauth2bindings_member_id"),
        "members_oauth2bindings",
        ["member_id"],
        unique=False,
    )
    op.create_table(
        "members_roles",
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.String(), nullable=False),
        sa.Column("startdate", app.models.types.FlexibleDate(), nullable=False),
        sa.Column("enddate", app.models.types.FlexibleDate(), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("member_id", "role_id", "startdate"),
    )
    op.create_table(
        "p4x_category_directs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("p4x_transaction_id", sa.Integer(), nullable=False),
        sa.Column("p4x_category_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["p4x_category_id"],
            ["p4x_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["p4x_transaction_id"],
            ["p4x_transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_p4x_category_directs_p4x_category_id"),
        "p4x_category_directs",
        ["p4x_category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_p4x_category_directs_p4x_transaction_id"),
        "p4x_category_directs",
        ["p4x_transaction_id"],
        unique=False,
    )
    op.create_table(
        "p4x_category_filter_hits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("p4x_transaction_id", sa.Integer(), nullable=False),
        sa.Column("p4x_category_filter_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["p4x_category_filter_id"],
            ["p4x_category_filters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["p4x_transaction_id"],
            ["p4x_transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "p4x_transaction_id",
            "p4x_category_filter_id",
            name="transaction_category_filter_id",
        ),
    )
    op.create_index(
        op.f("ix_p4x_category_filter_hits_p4x_category_filter_id"),
        "p4x_category_filter_hits",
        ["p4x_category_filter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_p4x_category_filter_hits_p4x_transaction_id"),
        "p4x_category_filter_hits",
        ["p4x_transaction_id"],
        unique=False,
    )
    op.create_table(
        "p4x_summary_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ordered_by", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("summary_start", app.models.types.FlexibleDate(), nullable=False),
        sa.Column("summary_end", app.models.types.FlexibleDate(), nullable=False),
        sa.Column("pid", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("finished_ok", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ordered_by"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "public_gallery_images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sha256_hash", sa.String(), nullable=False),
        sa.Column("extension", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("caption", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["members.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256_hash"),
    )
    op.create_index(
        op.f("ix_public_gallery_images_sort_order"),
        "public_gallery_images",
        ["sort_order"],
        unique=False,
    )
    op.create_table(
        "archive_file_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("archive_file_id", sa.Integer(), nullable=False),
        sa.Column("archive_store_item_id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["archive_file_id"],
            ["archive_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["archive_store_item_id"],
            ["archive_store_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("archive_file_versions")
    op.drop_index(
        op.f("ix_public_gallery_images_sort_order"), table_name="public_gallery_images"
    )
    op.drop_table("public_gallery_images")
    op.drop_table("p4x_summary_orders")
    op.drop_index(
        op.f("ix_p4x_category_filter_hits_p4x_transaction_id"),
        table_name="p4x_category_filter_hits",
    )
    op.drop_index(
        op.f("ix_p4x_category_filter_hits_p4x_category_filter_id"),
        table_name="p4x_category_filter_hits",
    )
    op.drop_table("p4x_category_filter_hits")
    op.drop_index(
        op.f("ix_p4x_category_directs_p4x_transaction_id"),
        table_name="p4x_category_directs",
    )
    op.drop_index(
        op.f("ix_p4x_category_directs_p4x_category_id"),
        table_name="p4x_category_directs",
    )
    op.drop_table("p4x_category_directs")
    op.drop_table("members_roles")
    op.drop_index(
        op.f("ix_members_oauth2bindings_member_id"), table_name="members_oauth2bindings"
    )
    op.drop_index(
        op.f("ix_members_oauth2bindings_id"), table_name="members_oauth2bindings"
    )
    op.drop_table("members_oauth2bindings")
    op.drop_table("members_logs")
    op.drop_table("members_keys")
    op.drop_table("members_badges")
    op.drop_table("contacts_logs")
    op.drop_table("archive_store_items")
    op.drop_table("archive_file_comments")
    op.drop_index(op.f("ix_p4x_transactions_valuation"), table_name="p4x_transactions")
    op.drop_index(op.f("ix_p4x_transactions_subject"), table_name="p4x_transactions")
    op.drop_index(
        op.f("ix_p4x_transactions_p4x_account_id"), table_name="p4x_transactions"
    )
    op.drop_index(op.f("ix_p4x_transactions_iban"), table_name="p4x_transactions")
    op.drop_index(
        op.f("ix_p4x_transactions_delegating_partner_type"),
        table_name="p4x_transactions",
    )
    op.drop_index(
        op.f("ix_p4x_transactions_delegating_partner_id"), table_name="p4x_transactions"
    )
    op.drop_index(op.f("ix_p4x_transactions_booking"), table_name="p4x_transactions")
    op.drop_index(op.f("ix_p4x_transactions_amount"), table_name="p4x_transactions")
    op.drop_table("p4x_transactions")
    op.drop_index(
        op.f("ix_p4x_category_filters_p4x_category_id"),
        table_name="p4x_category_filters",
    )
    op.drop_index(
        op.f("ix_p4x_category_filters_p4x_account_id"),
        table_name="p4x_category_filters",
    )
    op.drop_table("p4x_category_filters")
    op.drop_index(op.f("ix_members_id"), table_name="members")
    op.drop_index(op.f("ix_members_email"), table_name="members")
    op.drop_table("members")
    op.drop_index(op.f("ix_contacts_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_table("archive_permissions")
    op.drop_table("states")
    op.drop_index(op.f("ix_standesdb_images_id"), table_name="standesdb_images")
    op.drop_table("standesdb_images")
    op.drop_index(op.f("ix_sent_emails_id"), table_name="sent_emails")
    op.drop_table("sent_emails")
    op.drop_table("roles")
    op.drop_index(op.f("ix_request_logs_id"), table_name="request_logs")
    op.drop_table("request_logs")
    op.drop_index(
        op.f("ix_personal_access_tokens_token"), table_name="personal_access_tokens"
    )
    op.drop_index(
        op.f("ix_personal_access_tokens_id"), table_name="personal_access_tokens"
    )
    op.drop_table("personal_access_tokens")
    op.drop_index(
        op.f("ix_password_reset_tokens_email"), table_name="password_reset_tokens"
    )
    op.drop_table("password_reset_tokens")
    op.drop_table("p4x_specialcontacts")
    op.drop_index(op.f("ix_p4x_partners_partner_id"), table_name="p4x_partners")
    op.drop_table("p4x_partners")
    op.drop_table("p4x_fees")
    op.drop_table("p4x_categories")
    op.drop_table("p4x_accounts")
    op.drop_table("orgs")
    op.drop_table("keys")
    op.drop_index(op.f("ix_client_user_agents_id"), table_name="client_user_agents")
    op.drop_table("client_user_agents")
    op.drop_table("badges")
    op.drop_table("archive_files")
    op.drop_table("archive_dirs")
    # ### end Alembic commands ###
