"""add public_gallery_images

Revision ID: eafb371929f8
Revises: 8817d8f25690
Create Date: 2026-07-16 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eafb371929f8"
down_revision: str | Sequence[str] | None = "8817d8f25690"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    No-op, like the initial baseline: this project's real schema source is
    `Base.metadata.create_all()` (run once per environment, see the P-migration
    runbook), not Alembic DDL. The autogenerated `op.create_table(...)` that
    used to live here created `public_gallery_images` with a FK to `members` -
    harmless against long-lived Dev/Prod databases (where `members` already
    exists from the original bootstrap), but it broke CI's fresh, empty
    Postgres service container, which never runs `create_all()` before
    `alembic upgrade head`.
    """


def downgrade() -> None:
    """Downgrade schema. No-op, see `upgrade()`."""
